spring:
  profiles:
    active: local

spring.batch.job.names: ${job.name:NONE}

---
spring:
  profiles: local
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect
        format_sql: true
        show_sql: true
  batch:
    jdbc:
      initialize-schema: never
  datasource:
      url: jdbc:oracle:thin:ffpstgdb1.koreanair.com:2003/CRMSTGAPPL
      username: batuser
      password: kal13ibm
      driver-class-name: oracle.jdbc.driver.OracleDriver
